"""uploader column added to the images table

Revision ID: 2a4d49bba2e3
Revises: fa3cad1f2cef
Create Date: 2024-11-20 00:42:19.975107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a4d49bba2e3'
down_revision = 'fa3cad1f2cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploader', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('uploader')

    # ### end Alembic commands ###
