"""image model upgrade

Revision ID: 2e339a7aab8a
Revises: 2a4d49bba2e3
Create Date: 2024-11-21 00:58:51.923731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e339a7aab8a'
down_revision = '2a4d49bba2e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('processed_file_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processed_file_url', sa.VARCHAR(length=200), nullable=False))

    # ### end Alembic commands ###
