"""Add timestamp to ImageModel

Revision ID: 7f80709b203b
Revises: 2e339a7aab8a
Create Date: 2024-11-29 00:09:42.608114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f80709b203b'
down_revision = '2e339a7aab8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
